CREATE ROLE master WITH LOGIN PASSWORD 'master2424';
CREATE ROLE viewer WITH LOGIN PASSWORD 'viewer2424';

GRANT CONNECT ON DATABASE ediary_db TO master;
GRANT CONNECT ON DATABASE ediary_db TO viewer;
