version: '3.9'

services:
  db:
    image: postgres
    container_name: ediary-postgres-master
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ediary-volume:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: ediary-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
  
  md-to-html:
    build: ./mdtohtml
    image: pandoc
    container_name: ediary-pandoc
    volumes:
      - ./README.md:/input/index.md
      - ./metaData/diagrams:/input/metaData/diagrams
      - ./nginx/readme:/output
    command: /entrypoint.sh
      
  back1:
    build: ./backend
    image: ediary-backend
    container_name: ediary-back-1
    env_file:
      - ./backend/back1.env
    ports:
      - "2424:2424"
    depends_on:
      - db

volumes:
  ediary-volume:
  pgadmin_data:
