version: '3.9'

services:
  db:
    image: postgres
    container_name: ediary-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ediary-volume:/var/lib/postgresql/data

volumes:
  ediary-volume: