version: '3.9'

services:
  db:
    image: postgres
    container_name: ediary-postgres-master
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ediary-volume:/var/lib/postgresql/data
  
  back1:
    build: ./backend
    container_name: ediary-back-1
    env_file:
      - ./backend/back1.env
    ports:
      - "2424:2424"
    depends_on:
      - db

volumes:
  ediary-volume: