CREATE ROLE master WITH LOGIN PASSWORD 'master2424';
CREATE ROLE viewer WITH LOGIN PASSWORD 'viewer2424';

GRANT CONNECT ON DATABASE ediary_db TO master;
GRANT USAGE ON SCHEMA public TO master;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO master;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO master;

GRANT CONNECT ON DATABASE ediary_db TO viewer;
GRANT USAGE ON SCHEMA public TO viewer;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO viewer;
