services:
  app-test:
    build:
      context: ..
      dockerfile: ./cicd/Dockerfile.test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./allure-report:/app/build/allure-report
      - ./allure-results:/app/build/allure-results
    env_file: 
      - ../backend/dev.env
    environment:
      - TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
      - DOCKER_HOST=unix:///var/run/docker.sock
