FROM eclipse-temurin:20-jdk

WORKDIR /app

COPY backend/gradlew backend/gradlew.bat backend/settings.gradle backend/build.gradle.kts* backend/build.gradle /app/
COPY backend/gradle /app/gradle

COPY backend/src /app/src

COPY cicd /app/cicd

RUN chmod +x ./gradlew
RUN chmod +x cicd/entrypoint.sh

ENTRYPOINT ["./cicd/entrypoint.sh"]
