spring:
  application:
    name: fakeDataGenerator

config:
  export:
    outputDir: "generatedData/"
    fileType:
      txt: true
      json: true
      csw: true
      sql: true
  generators:
    package: "org.srd.fakeDataGenerator.service.illustration"

logging:
  level:
    root: ERROR
    org:
      srd: DEBUG
      springframework:
        boot:
          autoconfigure: WARN
  file:
    name: logs/fakeDataGenerator.log

faker:
  locale: ru
  seed: 228
