spring:
  application:
    name: fakeDataGenerator

config:
  export:
    outputDir: "generatedData/"
    fileType:
      txt: false
      json: true
      csw: false
      sql: true
  generators:
    package: "org.srd.fakeDataGenerator.implementations.eDiary"
  models:
    baseGeneratedNumber: 100

logging:
  level:
    root: ERROR
    org:
      srd: DEBUG
      springframework:
        boot:
          autoconfigure: WARN
  file:
    name: logs/fakeDataGenerator.log

faker:
  locale: ru
  seed: 228
