version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: ediary-nginx
    ports:
      - "2323:2323"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
      - ./swagger.conf:/etc/nginx/includes/swagger.conf
      - ../frontend/ediary_vue/dist/:/usr/share/nginx/html/legacy
