version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: ediary-nginx
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./default.conf:/etc/nginx/conf.d/default.conf
